---
- name: db1-fs
  group: "[vbox-si-fs]"
  box: oravirt/ol73
  ram: 3072
  cpu: 1
  ip: 192.168.9.61
  os_extra_disk: "yes"
  os_extra_disk_size: 50
  os_num_extra_disk: 1
  db_extra_disk: "yes"
  db_extra_disk_size: 50
  db_num_extra_disk: 1
  private_key: /Users/miksan/.vagrant.d/insecure_private_key

