- basename_vm: db-fs-
  num_vm: 1
  hostgroup: vbox-si-fs
  domain: internal.lab
  box: oravirt/ol75
  vagrant_user: vagrant
  vagrant_pass: vagrant
  #vagrant_private_key: /vagrant/base-provision/insecure_private_key
  ram: 3072
  cpu: 1
  base_pub_ip: 192.168.9.61
  synced_folders:
     - {src: swrepo, dest: /media/swrepo}
     #- {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
  create_local_disk: true
  local_disks:
     - {name: u01, size: 75, count: 1}
     - {name: u02, size: 75, count: 1}
  create_shared_disk: false
  provisioning: extra-provision/ansible-oracle/vbox-si-fs-install.yml
  provisioning_env_override: true
